### PR TITLE
Set up the source and header files for the IDE

### PR DESCRIPTION
**Pull request by zebmason**
Set the source_group for the IDE

### CODE REVIEW

**Comment by zdroid** [comment]
There is also https://stackoverflow.com/questions/3201154/automatically-add-all-files-in-a-folder-to-a-target-using-cmake, so that may be the better option

**Comment by zebmason** [comment]
@zdroid Bemused as my commit sets the folder for the IDE a la vcxproj.filters file, it doesn't create the list of files which is what is discussed on stackoverflow

**Comment by zdroid** [comment]
Your proposal still manually lists all `.cpp` and `.h` files, while the one on the link above lists them all automatically. What I wanted to say is that this project may use that approach to further simplify what you proposed. :wink:

**Comment by zebmason** [comment]
@matt-gretton-dann Agree as I've been caught out in the past by doing a 
file(GLOB ...

**Pull request merged**
