### PR TITLE
stdio.h -> cstdio

### PR DESCRIPTION
**Pull request by zdroid**

### CODE REVIEW

**Comment by zdroid** [comment]
Any news on this and #301, #303? These aren't major changes.

**Comment by zdroid** [comment]
Is there a reason why this PR wasn't merged, but others were?

**Comment by weshinsley** [comment]
Give me a chance! ;-) 

On the second one the CentOS test failed for no obvious reason. I'm going to explore that and get a green light before doing more merging...

**Comment by weshinsley** [comment]
The CentOS failure is nothing to do with the code. Rather than re-test and wait, I've resolved above conflicts (just the results of PR #301 and PR #303), and we'll see whether CentOS is happier this time.

**Comment by zdroid** [comment]
Yep, it looks like an issue with the server from which dependencies are downloaded.

**Comment by weshinsley** [comment]
Seems to be running through fine on merging this one... :-)

**Pull request closed without merging**
