### PR TITLE
Update CMake for the containers

### PR DESCRIPTION
**Pull request by zebmason**
One last try as I managed to search code in GitHub effectively at last

### CODE REVIEW

**Comment by zebmason** [comment]
@matt-gretton-dann Two methods to build because either bionic or alpine fail

**Comment by zebmason** [comment]
@matt-gretton-dann 
CMake upgraded across all containers as you asked for

**Comment by zebmason** [comment]
@weshinsley Just rebased and OpenSuSe has started doing random errors. So converted to draft and will have a play tonight.

**Comment by zebmason** [comment]
@weshinsley Looks like they changed the containers again. I remember Matt having to make some changes to the CI in the past when they did that.

**Comment by weshinsley** [comment]
Since this was requested by Matt, looks good to me, and all the tests are passing, I'll merge in order to enable onward development...

**Comment by weshinsley** [comment]
(Ref Issue #233)

**Pull request merged**
