### PR TITLE
Multrealisations

### PR DESCRIPTION
**Pull request by NeilFerguson**
Multiple improvements - most significant is reinstating accurate averaging over realisations with calibration of each one, plus improvements to calibration and to handling of partial place closure.

### CODE REVIEW

**Comment by dlaydon** [comment]
Also there were a few conflicts now in some #pragma loops, because of some cleaning done in https://github.com/mrc-ide/covid-sim/pull/264. It's well worth keeping those changes so I've resolved them accordingly. As ever though, a little scrutiny would be helpful, so @NeilFerguson and @matt-gretton-dann can you check you're happy with https://github.com/mrc-ide/covid-sim/pull/306/commits/d9a0601e33a6714422fea9d415bb7f8ff4cc70fc?

**Comment by zebmason** [comment]
Is CMakeSettings.json required or was it checked in by mistake?

**Comment by NeilFerguson** [comment]
Mistake

Best,

Neil
________________________________

**Comment by matt-gretton-dann** [comment]
Three commits:
 * Fix the build following a missed variable declaration as a result of the merge.
 * Updated test results
 * Removed CMakeSettings.json

**Pull request merged**
