### PR TITLE
Update model-overview.md

### PR DESCRIPTION
**Pull request by phelps-sg**
Added link to supplementary information for Ferguson et al 2005.  Provided citation details in links to papers.

### CODE REVIEW

**Comment by matt-gretton-dann** [comment]
@z80coder or @dlaydon I would appreciate your review of these changes.

**Comment by dlaydon** [comment]
Not sure if we need the papers displayed at the top of the doc when they are listed both at the bottom and prominently in the README.md, but open to suggestion

**Comment by phelps-sg** [comment]
I also added a new link to the supplementary material. What is your specific concern in having the citations as the link text rather than url? If the paper citations at the bottom are now redundant then would it make sense to remove them so that there are just one set of clickable references rather than duplicating them?

**Comment by phelps-sg** [comment]
Just to clarify I did not add the papers at the top, I just added text descriptions to the raw URLs that were already there.

**Comment by ozmorph** [comment]
I think the confusion with this pull request is the result of a simple tree-conflict.

The branch being merged is conflicting with the changes brought in from #164 that was merged yesterday. That branch deduplicated the links in `model-overview.md` and now you're seeing them be added back in on this branch because of that.

The easiest solution would be to rebase this branch onto Master.

**Comment by phelps-sg** [comment]
Since edited this file in the github IDE it might be simpler if close this PR and redo the changes.

**Pull request closed without merging**
